pipeline{
    // installer l'enviroonement
    // installer node js
    agent {
        docker {image "playwright/chromium:playwright-1.56.1"
            args "--user=root --entrypoint=''"
        }
    }

    // git clone
    // npm install
    // npx playwright test --project=chromium --grep=@smoke
    stages {
        stage("demmarer le projets"){
            steps{
                //creer supprimer le repo
                sh "rm -rf repo "
              
                //cloner son dossier
                sh "git clone https://github.com/Ausni/Playwright_jenkins.git repo"
             
                sh "echo 'node --version' "
                sh  dir('repo'){
                    sh"npm install"
                    sh "npx playwright test --project=chromium"
                }
             }
        }

        
    }

}
